#ifndef XYLEM_H
#define XYLEM_H

#include "04Component.h"
#include "02Soils.h"
#include "05Root.h"
#include "06Stem.h"
#include "07Leaf.h"

/*

    Each layer layer contains a root element connected to a rhizosphere component.

    There are five horizontal layers.

    Biomass_fraction is determined as follows:

    \Beta = 1 - \beta^d, where \Beta is fraction of biomass above depth d in cm, 
    and 0 < \beta < 1. Max root depth set at \Beta = 0.995.

*/

struct SoilLayer {
    RootComponent root;
    RhizosphereComponent rhizosphere;
    double  biomass_fraction,
            kkmax,
            vert_distance,
            layer_depth,
            depth,
            radius,
            length;
};

class XylemComponent {

    public:

        XylemComponent() {};
        ~XylemComponent();
        
        LeafComponent leaf;
        StemComponent stem;
        SoilLayer top_soil;
        std::vector<SoilLayer*> soils;

        /* Used for something! */
        double rough,
               zdispl,
               zh;

        /*

            If only one soil layer, all components are in series and the E_i
            is identical for all components and equal to canopy E. Then we can
            just use individual integral transform for each component.
        
            If root and rhizosphere components are partitioned into N parallel 
            paths that drain given a known P_soil. There are then N + 1 unknown 
            pressures:

            E_{i(rhizosphere)} - E_{i(root)} = 0, root surface pressure
            \sum{E_{i(root)}} - E = 0, root crown pressure

            This is solved via multidimensional Newton Rhaphson.

            E_i is determined via Component:flow_rate(). E is specified. Stem
            and leaf pressures are obtained from Component:flow_rate() and
            supply function generated by incrementing E from zero.

            Inputs:
                - 

            Outputs:
                - 
        
        */
        double& calc_pressure();

        /*

            After every time step, bulk soil water content and boundary 
            conditions must be recalculated for every soil layer. Net flow from 
            the previous time step is added to the old water content to obtain
            new water content. Net flow is the sum of:

                1. Flow across rhizosphere. This is calculated along E(P_c)
                   function
                2. Rain or irrigation in previous time step
                3. Soil evaporation
                4. Redistribution between layers, estimated from integral
                   transform of van Genuchten K(P_s) function.

        */
        void calc_net_flow(const double &p_inc, const double &k_min);

        // function that accounts for xylem cavitation fatigue
        double fatigue(double &b_wb, const double &sapwood_t, const double &conduit_d, const double &max_plc_x);
};

#endif